name: feather-light
on:
    push:
        branches:
          ["main"]
    pull_request:
        branches:
          ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v4
              - uses: actions/setup-python@v5
                with:
                  python-version:'3.10'
                run: |
                  python -m pip install pipx
                  pipx install poetry
                  poetry build

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
          run: poetry run python -m unittest discover -s tests -p "*_test.py"

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
          run: echo "Deployment parts"

